name: todo_bloc
description: "todo_bloc"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 0.1.0 # Версия проекта
environment: # Настройка окружения проекта
  sdk: '>=3.0.5 <4.0.0' # Версия SDK для проекта
dependencies: # Зависимости проекта
  flutter_staggered_grid_view: 0.7.0
  flutter: # Зависимость Flutter SDK
    sdk: flutter
  cupertino_icons: ^1.0.5 # Зависимость для иконок iOS в стиле Cupertino
  uuid: ^3.0.7 # Зависимость для генерации уникальных идентификаторов
  flutter_slidable: ^3.0.0 # Зависимость для создания скользящих элементов в интерфейсе
  hydrated_bloc: ^9.1.2 # Зависимость для установки прослойки между блоками состояний и хранилищем
  path_provider: ^2.0.15 # Зависимость для получения информации о файловой системе устройства
  flutter_bloc: ^8.1.3 # Зависимость для работы с блоками состояний
  equatable: ^2.0.5 # Зависимость для упрощения сравнения объектов
  meta: ^1.9.1 # Зависимость для применения метаданных к классам и методам
  bloc: ^8.1.2 # Зависимость для реализации паттерна блоков состояний
dev_dependencies: # Зависимости для разработки проекта
  flutter_test: # Зависимость для тестирования Flutter приложений
    sdk: flutter
  flutter_lints: ^2.0.0 # Зависимость для проверки соответствия кода рекомендациям по стилю
flutter: # Настройки Flutter
uses-material-design: true # Использование дизайна в стиле Material Design
